language: cpp
env:
 # We'll test against only a single library example, and only for uno, but you could add more combinations
 # https://github.com/arduino/Arduino/blob/master/build/shared/manpage.adoc
 - BOARD=arduino:avr:uno NAME=FabScanArduinoFirmware
#  - BOARD=attiny:avr:attiny85 NAME=$NullStreamExample

compiler:
 - gcc

before_install:
 - sudo apt-get update -qq && sudo apt-get install -qq avr-libc gcc-avr 

install:
 # arduino
 - wget https://downloads.arduino.cc/arduino-cli/arduino-cli-latest-linux64.tar.bz2
 - tar -xvfj arduino-cli-latest-linux64.tar.bz2
 - chmod a+x arduino-cli-0.3.7-alpha.preview-linux64
 - sudo mv arduino-cli-0.3.7-alpha.preview-linux64 /usr/local/share/arduino-cli

 # you could add attiny the extra attiny board package
# - wget https://github.com/damellis/attiny/archive/ide-1.6.x.zip
# - unzip ide-1.6.x.zip
# - sudo mv attiny-ide-1.6.x/attiny /usr/local/share/arduino/hardware/

before_script:
 # arduino requires an X server even with command line
 # https://github.com/arduino/Arduino/issues/1981
 #- Xvfb :1 -screen 0 1024x768x16 &> xvfb.log &
 # put your source files in a folder under a new libraries folder
 #- sudo mkdir -p /usr/src/arduino/libraries
 # sudo ln -s $TRAVIS_BUILD_DIR/$NAME /usr/src/arduino/libraries/$NAME

script:
 - cd $TRAVIS_BUILD_DIR/$NAME
 - make
